spring.application.name=hospital-token-queue

# ===== EDIT THESE 3 LINES with your own MySQL details =====
# createDatabaseIfNotExist=true means you don't even need to manually
# create the database first -- MySQL will create it the first time you run the app.
spring.datasource.url=jdbc:mysql://localhost:3306/smartqueuedb
spring.datasource.username=root
spring.datasource.password=@Vdhesh27

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# update = Hibernate creates the "tokens" table automatically from Token.java
# the first time you run the app, and updates it if you change the entity later.
spring.jpa.hibernate.ddl-auto=update

# Prints the actual SQL Hibernate generates in your console -- useful for learning.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
